all: compile execute1 execute2 execute3

compile: 
	gcc djikstra.c -o djikstra

execute1: 
	./djikstra -f exemplo.txt -i 1 -l 5

execute2: 
	./djikstra -f exemplo.txt -i 1

execute3: 
	./djikstra -f -s exemplo.txt -i 1